---
- hosts: all
  vars_files:
    - vars/external_vars.yml
  environment:
    REDIS_HOST: "{{redis_host}}"
    REDIS_PORT: "{{redis_port}}"
  
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install Dependencies
      apt: name={{ item }} state=present
      with_items:
       - git
       - supervisor
       - apt-transport-https
       - ca-certificates
       - python-setuptools
       - python-pip

    - name: Supervisor conf
      template: 
        src=sandbox_conf.j2
        dest=/etc/supervisor/conf.d/sandbox.conf
    
    - name: Install Dependencies  
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
    
    - name: Change docker.list
      template: 
        src=docker_list.j2 
        dest=/etc/apt/sources.list.d/docker.list

    - name: Update sources
      apt: update_cache=yes
    
    - name: Install docker
      apt: name=docker-engine state=present

    - name: Clone sandbox  
      git: repo=https://github.com/mariosky/sandbox.git dest=/home/sandbox
    
    - name: docker-py 
      pip: name=docker-py
    
    - name: redis-py    
      pip: name=redis

    - name: pull sandbox image (this may take a while)
      command: docker pull mariosky/sandbox_worker:latest
    
    - name: chmod
      file: path=/var/run/docker.sock  mode='o+rwx'




    



        
       


        